CREATE TABLE Majors(
MajorID INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(15) NOT NULL
)

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber INT NOT NULL,
StudentName NVARCHAR(20) NOT NULL,
MajorID INT NOT NULL,

CONSTRAINT FK_MajorID_Majors FOREIGN KEY (MajorID) REFERENCES Majors(MajorID)
)

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATETIME2 NOT NULL,
PaymentAnount DECIMAL(15, 2) NOT NULL,
StudentID INT NOT NULL,

CONSTRAINT FK_StudentID_Students FOREIGN KEY (StudentId) REFERENCES Students(StudentID)
)

CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName NVARCHAR(20) NOT NULL
)

CREATE TABLE Agenda(
StudentID INT,
SubjectID INT,

CONSTRAINT PK_StudentID_SubjectID PRIMARY KEY(StudentID, SubjectID),
CONSTRAINT FK_StudentID FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
CONSTRAINT FK_SubjectID FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
)